### ISSUE TITLE
Get idField from service.id if available

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers-reactive#59]
`feathers-service-tests` guarantees `id` to be present on commonly used (i.e. official) services.
Reading the appropriate value for `idField` from `service.id` would reduce boilerplate, especially when you have both `id` and `_id` services. Any thoughts on this?

**Comment by daffl** [comment]
This might be rather tricky because services know about their id field on the __server side__ but not on the client. Currently there isn't really a way to communicate this to the client. We could add service introspection but it will need a lot of thought to decide what it should expose and how to properly secure it.
